#ifndef DISPLAYFEATURE_VERSION_H
#define DISPLAYFEATURE_VERSION_H

#define DF_VERSION_MAJOR @PROJECT_VERSION_MAJOR@
#define DF_VERSION_MINOR @PROJECT_VERSION_MINOR@
#define DF_VERSION_PATCH @PROJECT_VERSION_PATCH@
#define DF_VERSION_STRING "@PROJECT_VERSION@"

#define DF_VERSION_ENCODE(maj,min,pat) \
    (((maj) << 16) | ((min) << 8) | (pat))

#define DF_VERSION \
    DF_VERSION_ENCODE(DF_VERSION_MAJOR, DF_VERSION_MINOR, DF_VERSION_PATCH)

#endif /* DISPLAYFEATURE_VERSION_H */
